//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinTaxEasy_Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int UserID { get; set; }
        public int AddressID { get; set; }
        public string AddressDescription { get; set; }
        public string AddressLine1 { get; set; }
        public string AdressLine2 { get; set; }
        public string Area { get; set; }
        public string Landmark { get; set; }
        public Nullable<int> CityID { get; set; }
        public int StateID { get; set; }
        public int CountryID { get; set; }
        public string PinCode { get; set; }
        public string MobileNumber1 { get; set; }
        public string MobileNumber2 { get; set; }
    
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual RegisteredUser RegisteredUser { get; set; }
        public virtual State State { get; set; }
    }
}
