//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinTaxEasy_Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.Addresses = new HashSet<Address>();
            this.States = new HashSet<State>();
        }
    
        public int CountyID { get; set; }
        public string CountryCode { get; set; }
        public string CountryName { get; set; }
        public int CurrencyID { get; set; }
    
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual ICollection<State> States { get; set; }
    }
}
