//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinTaxEasy_Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.UserPrivileges = new HashSet<UserPrivilege>();
            this.RegisteredUsers = new HashSet<RegisteredUser>();
        }
    
        public int RoleID { get; set; }
        public string RoleName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    
        public virtual ICollection<UserPrivilege> UserPrivileges { get; set; }
        public virtual ICollection<RegisteredUser> RegisteredUsers { get; set; }
    }
}
